// GENERATED by scripts/sync-barrel-shims.ts — do not edit by hand.
// Types for the used-functions runtime shim: the package's own barrel
// declarations, so every import site keeps its exact function type.
export * from 'date-fns';
