// GENERATED by scripts/sync-barrel-shims.ts — do not edit by hand.
// Types for the used-icons runtime shim: the package's own barrel
// declarations, so every import site keeps its exact icon type.
export * from '@tamagui/lucide-icons-2';
