// GENERATED by scripts/sync-barrel-shims.ts — do not edit by hand.
// Re-exports every @tamagui/lucide-icons-2 icon the repo imports,
// from per-icon modules (see that script for why the barrel cannot
// tree-shake under CJS resolution). Regenerated on every build.

export { AlertCircle } from '@tamagui/lucide-icons-2/dist/esm/icons/AlertCircle.mjs';
export { AlertTriangle } from '@tamagui/lucide-icons-2/dist/esm/icons/AlertTriangle.mjs';
export { Bell } from '@tamagui/lucide-icons-2/dist/esm/icons/Bell.mjs';
export { BookOpen } from '@tamagui/lucide-icons-2/dist/esm/icons/BookOpen.mjs';
export { Brain } from '@tamagui/lucide-icons-2/dist/esm/icons/Brain.mjs';
export { CalendarDays } from '@tamagui/lucide-icons-2/dist/esm/icons/CalendarDays.mjs';
export { Check } from '@tamagui/lucide-icons-2/dist/esm/icons/Check.mjs';
export { CheckCircle } from '@tamagui/lucide-icons-2/dist/esm/icons/CheckCircle.mjs';
export { CheckCircle2 } from '@tamagui/lucide-icons-2/dist/esm/icons/CheckCircle2.mjs';
export { ChevronDown } from '@tamagui/lucide-icons-2/dist/esm/icons/ChevronDown.mjs';
export { ChevronLeft } from '@tamagui/lucide-icons-2/dist/esm/icons/ChevronLeft.mjs';
export { ChevronRight } from '@tamagui/lucide-icons-2/dist/esm/icons/ChevronRight.mjs';
export { ClipboardCopy } from '@tamagui/lucide-icons-2/dist/esm/icons/ClipboardCopy.mjs';
export { Coffee } from '@tamagui/lucide-icons-2/dist/esm/icons/Coffee.mjs';
export { Eye } from '@tamagui/lucide-icons-2/dist/esm/icons/Eye.mjs';
export { EyeOff } from '@tamagui/lucide-icons-2/dist/esm/icons/EyeOff.mjs';
export { Flame } from '@tamagui/lucide-icons-2/dist/esm/icons/Flame.mjs';
export { Footprints } from '@tamagui/lucide-icons-2/dist/esm/icons/Footprints.mjs';
export { GraduationCap } from '@tamagui/lucide-icons-2/dist/esm/icons/GraduationCap.mjs';
export { HandHeart } from '@tamagui/lucide-icons-2/dist/esm/icons/HandHeart.mjs';
export { Heart } from '@tamagui/lucide-icons-2/dist/esm/icons/Heart.mjs';
export { HelpCircle } from '@tamagui/lucide-icons-2/dist/esm/icons/HelpCircle.mjs';
export { Home } from '@tamagui/lucide-icons-2/dist/esm/icons/Home.mjs';
export { Info } from '@tamagui/lucide-icons-2/dist/esm/icons/Info.mjs';
export { Languages } from '@tamagui/lucide-icons-2/dist/esm/icons/Languages.mjs';
export { Lock } from '@tamagui/lucide-icons-2/dist/esm/icons/Lock.mjs';
export { Mail } from '@tamagui/lucide-icons-2/dist/esm/icons/Mail.mjs';
export { Menu } from '@tamagui/lucide-icons-2/dist/esm/icons/Menu.mjs';
export { Minus } from '@tamagui/lucide-icons-2/dist/esm/icons/Minus.mjs';
export { Monitor } from '@tamagui/lucide-icons-2/dist/esm/icons/Monitor.mjs';
export { Moon } from '@tamagui/lucide-icons-2/dist/esm/icons/Moon.mjs';
export { Music } from '@tamagui/lucide-icons-2/dist/esm/icons/Music.mjs';
export { Package } from '@tamagui/lucide-icons-2/dist/esm/icons/Package.mjs';
export { Play } from '@tamagui/lucide-icons-2/dist/esm/icons/Play.mjs';
export { Plus } from '@tamagui/lucide-icons-2/dist/esm/icons/Plus.mjs';
export { Search } from '@tamagui/lucide-icons-2/dist/esm/icons/Search.mjs';
export { Settings } from '@tamagui/lucide-icons-2/dist/esm/icons/Settings.mjs';
export { Sparkles } from '@tamagui/lucide-icons-2/dist/esm/icons/Sparkles.mjs';
export { Star } from '@tamagui/lucide-icons-2/dist/esm/icons/Star.mjs';
export { Sun } from '@tamagui/lucide-icons-2/dist/esm/icons/Sun.mjs';
export { Target } from '@tamagui/lucide-icons-2/dist/esm/icons/Target.mjs';
export { TrendingUp } from '@tamagui/lucide-icons-2/dist/esm/icons/TrendingUp.mjs';
export { Trophy } from '@tamagui/lucide-icons-2/dist/esm/icons/Trophy.mjs';
export { User } from '@tamagui/lucide-icons-2/dist/esm/icons/User.mjs';
export { Waves } from '@tamagui/lucide-icons-2/dist/esm/icons/Waves.mjs';
export { X } from '@tamagui/lucide-icons-2/dist/esm/icons/X.mjs';
export { XCircle } from '@tamagui/lucide-icons-2/dist/esm/icons/XCircle.mjs';
