// metro.config.js
// Load-bearing: forces Metro to use traditional CJS resolution, bypassing
// the ESM `import.meta` issue that breaks web hydration.
//
// Zustand v5's `devtools` middleware (re-exported via `zustand/middleware`,
// which arqavellum pulls in through `persist`/`createJSONStorage`) references
// `import.meta.env.MODE`. When Metro resolves packages via the `exports`
// field in their package.json (the modern ESM-aware default), the ESM
// build of `zustand/middleware` is selected and the `import.meta` syntax
// flows through to the web bundle unchanged. Expo Web emits the bundle as
// a classic script (`<script src="..." defer>`, no `type="module"`), so
// the browser throws `SyntaxError: Cannot use 'import.meta' outside a
// module` at parse time. The entire bundle fails to execute and React
// never hydrates — the page looks rendered (SSR HTML is shipped) but
// nothing is interactive.
//
// Disabling `unstable_enablePackageExports` and forcing the `require` /
// `browser` condition names makes Metro pick the CJS build of every
// dependency, which uses `process.env.NODE_ENV` instead of `import.meta.env`
// and parses cleanly as a classic script.

const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// NUCLEAR OPTION: Disable package.json exports entirely.
// This forces Metro to use traditional CJS resolution, bypassing
// ESM/import.meta issues.
config.resolver.unstable_enablePackageExports = false;

// Web-first resolution order.
config.resolver.unstable_conditionNames = ['browser', 'require', 'default'];

// BARREL SHIMS: the CJS resolution above defeats tree-shaking for barrel
// packages — @tamagui/lucide-icons-2 (one icon pulls all 3520) and
// date-fns (one function pulls the whole library). The exact barrel
// specifiers resolve to shims/*.js, GENERATED by
// scripts/sync-barrel-shims.ts from the repo's actual imports (chained
// before every expo command in package.json). If a shim is missing
// — someone ran the expo CLI directly — regenerate them here so no
// invocation can resolve a stale or absent shim.
const path = require('path');
const { existsSync } = require('fs');
const { spawnSync } = require('child_process');
const LUCIDE_SHIM = path.resolve(__dirname, 'shims/lucide-icons-2.js');
const DATE_FNS_SHIM = path.resolve(__dirname, 'shims/date-fns.js');
if (!existsSync(LUCIDE_SHIM) || !existsSync(DATE_FNS_SHIM)) {
  spawnSync('bun', ['run', 'scripts/sync-barrel-shims.ts'], { stdio: 'inherit', cwd: __dirname });
}
const BARREL_SHIMS = {
  '@tamagui/lucide-icons-2': LUCIDE_SHIM,
  'date-fns': DATE_FNS_SHIM,
  // Not a barrel — a capability stub: themed() throws provider-less, and
  // the starter mounts no TamaguiProvider (see shims/helpers-icon.js).
  '@tamagui/helpers-icon': path.resolve(__dirname, 'shims/helpers-icon.js'),
};
// Dev surfaces (the design-system showcase under app/dev/) resolve to an
// empty stub in every export, deterministically — NODE_ENV at
// metro-config load time is NOT reliable across invocation styles. The
// dev scripts opt in via EXPO_PUBLIC_DEV_SURFACES=1 (see package.json).
const DEV_DIR = path.resolve(__dirname, 'app/dev');
const DEV_ROUTE_STUB = path.resolve(__dirname, 'shims/dev-route-stub.tsx');
const devSurfacesEnabled = process.env.EXPO_PUBLIC_DEV_SURFACES === '1';
const defaultResolveRequest = config.resolver.resolveRequest;
config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (BARREL_SHIMS[moduleName]) {
    return { type: 'sourceFile', filePath: BARREL_SHIMS[moduleName] };
  }
  const resolved = defaultResolveRequest
    ? defaultResolveRequest(context, moduleName, platform)
    : context.resolveRequest(context, moduleName, platform);
  if (!devSurfacesEnabled && resolved?.type === 'sourceFile' && resolved.filePath?.startsWith(DEV_DIR)) {
    return { type: 'sourceFile', filePath: DEV_ROUTE_STUB };
  }
  return resolved;
};

module.exports = config;
