#!/usr/bin/env bun
// scripts/sync-barrel-shims.ts
//
// Generates the used-symbol shims for the barrel packages that cannot
// tree-shake under this repo's Metro config:
//
//   shims/lucide-icons-2.js  — every @tamagui/lucide-icons-2 icon the
//                              repo imports, re-exported from per-icon
//                              modules.
//   shims/date-fns.js        — every date-fns function the repo imports,
//                              re-exported from per-function modules.
//
// WHY THEY EXIST: metro.config.js runs with `unstable_enablePackageExports
// = false` (the CJS nuclear option — see that file for the zustand
// import.meta story). CJS resolution cannot tree-shake barrels: importing
// ONE icon pulls all 3520 (measured: over a megabyte of minified bundle
// for a few dozen used icons); importing a handful of date-fns functions
// pulls the whole library. metro.config.js resolves the exact barrel
// specifiers to the generated shims, which re-export only what the repo
// uses (Metro still picks the .native.js twin per platform on native).
//
// Chained before every expo command in package.json (and regenerated by
// metro.config.js if missing), so a shim can never go stale: add an
// import anywhere and the next build picks it up automatically.
//
// Exits 1 with a loud message if an imported name has no per-module file
// in node_modules (typo'd name) — that error should fail the build, not
// surface as a blank glyph or a runtime undefined.

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(__dirname, '..');

// Source roots scanned for barrel imports (everything except the shims
// themselves, build output, and node_modules).
const SCAN_DIRS = [
  'app',
  'components',
  'constants',
  'context',
  'hooks',
  'lib',
  'navigation',
  'services',
  'shared',
  'stores',
  'utils',
];

/** Extract the imported symbol names from one brace block. */
function parseNames(blob: string): string[] {
  const names: string[] = [];
  for (let raw of blob.split(',')) {
    raw = raw.replace(/^type\s+/, '').trim();
    // aliased imports (`X as Y`) ship under the ORIGINAL name
    const original = raw.split(/\s+as\s+/)[0].trim();
    if (original.length > 0) names.push(original);
  }
  return names;
}

/** All names imported from `specifier` across the source roots. */
function collectImportedNames(specifier: string): Set<string> {
  const names = new Set<string>();
  const importRe = new RegExp(
    `import\\s+(?:type\\s+)?\\{([^}]+)\\}\\s*from\\s*['"]${specifier.replace(/\//g, '\\/')}['"];?`,
    'g',
  );
  for (const dir of SCAN_DIRS.map((d) => join(ROOT, d))) {
    for (const file of listSourceFiles(dir)) {
      const src = readFileSync(file, 'utf8');
      for (const m of src.matchAll(importRe)) {
        for (const name of parseNames(m[1])) names.add(name);
      }
    }
  }
  return names;
}

function listSourceFiles(dir: string): string[] {
  const out: string[] = [];
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listSourceFiles(full));
    else if (/\.(tsx?|jsx?)$/.test(entry.name)) out.push(full);
  }
  return out;
}

function die(message: string): never {
  console.error(`  ✗ sync-barrel-shims: ${message}`);
  process.exit(1);
}

/** Write a file if its content changed; returns whether it changed. */
function writeIfChanged(path: string, content: string): boolean {
  const changed = !existsSync(path) || readFileSync(path, 'utf8') !== content;
  if (changed) writeFileSync(path, content);
  return changed;
}

export function syncIconShim(): { icons: string[]; changed: boolean } {
  const packageDir = join(ROOT, 'node_modules/@tamagui/lucide-icons-2');
  const modulesDir = join(packageDir, 'dist/esm/icons');
  if (!existsSync(modulesDir)) {
    die('node_modules/@tamagui/lucide-icons-2 is not installed.');
  }

  const names = collectImportedNames('@tamagui/lucide-icons-2');
  const missing = [...names].filter((n) => !existsSync(join(modulesDir, `${n}.mjs`)));
  if (missing.length > 0) {
    die(
      `imported icon(s) with no per-icon module in @tamagui/lucide-icons-2 (typo?):\n    ${missing.join(', ')}`,
    );
  }

  const icons = [...names].sort();
  const js =
    '// GENERATED by scripts/sync-barrel-shims.ts — do not edit by hand.\n' +
    '// Re-exports every @tamagui/lucide-icons-2 icon the repo imports,\n' +
    '// from per-icon modules (see that script for why the barrel cannot\n' +
    '// tree-shake under CJS resolution). Regenerated on every build.\n\n' +
    icons
      .map((n) => `export { ${n} } from '@tamagui/lucide-icons-2/dist/esm/icons/${n}.mjs';`)
      .join('\n') +
    '\n';

  const dts =
    '// GENERATED by scripts/sync-barrel-shims.ts — do not edit by hand.\n' +
    "// Types for the used-icons runtime shim: the package's own barrel\n" +
    '// declarations, so every import site keeps its exact icon type.\n' +
    "export * from '@tamagui/lucide-icons-2';\n";

  mkdirSync(join(ROOT, 'shims'), { recursive: true });
  const jsChanged = writeIfChanged(join(ROOT, 'shims/lucide-icons-2.js'), js);
  const dtsChanged = writeIfChanged(join(ROOT, 'shims/lucide-icons-2.d.ts'), dts);
  return { icons, changed: jsChanged || dtsChanged };
}

export function syncDateFnsShim(): { functions: string[]; changed: boolean } {
  const packageDir = join(ROOT, 'node_modules/date-fns');
  if (!existsSync(packageDir)) {
    die('node_modules/date-fns is not installed.');
  }

  const names = collectImportedNames('date-fns');
  const missing = [...names].filter((n) => !existsSync(join(packageDir, `${n}.js`)));
  if (missing.length > 0) {
    die(
      `imported date-fns function(s) with no per-function module (typo?):\n    ${missing.join(', ')}`,
    );
  }

  const functions = [...names].sort();
  const js =
    '// GENERATED by scripts/sync-barrel-shims.ts — do not edit by hand.\n' +
    '// Re-exports every date-fns function the repo imports, from\n' +
    '// per-function modules (see that script for why the barrel cannot\n' +
    '// tree-shake under CJS resolution). Regenerated on every build.\n\n' +
    functions.map((n) => `export { default as ${n} } from 'date-fns/${n}.js';`).join('\n') +
    '\n';

  const dts =
    '// GENERATED by scripts/sync-barrel-shims.ts — do not edit by hand.\n' +
    "// Types for the used-functions runtime shim: the package's own barrel\n" +
    '// declarations, so every import site keeps its exact function type.\n' +
    "export * from 'date-fns';\n";

  mkdirSync(join(ROOT, 'shims'), { recursive: true });
  const jsChanged = writeIfChanged(join(ROOT, 'shims/date-fns.js'), js);
  const dtsChanged = writeIfChanged(join(ROOT, 'shims/date-fns.d.ts'), dts);
  return { functions, changed: jsChanged || dtsChanged };
}

// Run directly (package.json chains it before every expo command).
if (import.meta.main) {
  const { icons, changed: iconsChanged } = syncIconShim();
  const { functions, changed: fnsChanged } = syncDateFnsShim();
  console.log(
    `  sync-barrel-shims: ${icons.length} icons${iconsChanged ? ' — shim regenerated' : ' — shim up to date'}, ` +
      `${functions.length} date-fns functions${fnsChanged ? ' — shim regenerated' : ' — shim up to date'}`,
  );
}
